name: ${COMPOSE_PROJECT_NAME:-cht-sync}
version: '3.8'

x-dbt-base: &dbt-common
  build: ./dbt/
  working_dir: /dbt/
  environment: &dbt-env
    POSTGRES_HOST: ${POSTGRES_HOST}
    POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_TABLE: ${POSTGRES_TABLE}
    POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
    ROOT_POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
    CHT_PIPELINE_BRANCH_URL: ${CHT_PIPELINE_BRANCH_URL}
    DATAEMON_INTERVAL: ${DATAEMON_INTERVAL}
    DBT_PACKAGE_TARBALL_URL: ${DBT_PACKAGE_TARBALL_URL}
    DBT_THREAD_COUNT: ${DBT_THREAD_COUNT}

services:
  couch2pg:
    build: ./couch2pg/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
    environment:
      <<: *dbt-env
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      COUCHDB_HOST: ${COUCHDB_HOST}
      COUCHDB_DBS: ${COUCHDB_DBS}
      COUCHDB_PORT: ${COUCHDB_PORT}
      COUCHDB_SECURE: ${COUCHDB_SECURE:-true}

  dbt:
    <<: *dbt-common
    profiles:
      - default
    environment:
      <<: *dbt-env
      DBT_SELECTOR: ''

  dbt-base:
    <<: *dbt-common
    profiles:
      - base-and-package
    environment:
      <<: *dbt-env
      DBT_SELECTOR: tag:base

  dbt-models:
    <<: *dbt-common
    profiles:
      - base-and-package
    depends_on:
      - dbt-base
    environment:
      <<: *dbt-env
      DBT_SELECTOR: package:${DBT_PACKAGE_NAME}

  dbt-contacts:
    <<: *dbt-common
    profiles:
      - test
    environment:
      <<: *dbt-env
      DBT_SELECTOR: tag:contacts

  dbt-reports:
    <<: *dbt-common
    profiles:
     - test
    depends_on:
      - dbt-contacts
    environment:
      <<: *dbt-env
      DBT_SELECTOR: tag:reports
