version: '3.7'

services:
  logstash:
    depends_on:
      - couchdb

  couchdb:
    image: couchdb
    restart: always
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}

  _couchdb_bootstrap:
    image: curlimages/curl
    depends_on:
      - couchdb

    # TODO => loop through COUCHDB_DBS to bootstrap
    command: -X PUT http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@couchdb:5984/${COUCHDB_DBS}
    restart: on-failure:5

  _couchdb_bootstrap_users:
    image: curlimages/curl
    depends_on:
      - couchdb
    command: -X PUT http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@couchdb:5984/_users
    restart: on-failure:5

  generator:
    image: python:3
    depends_on:
      - couchdb
    command: python3 /code/data-generator.py
    environment:
      - COUCHDB_URL=http://couchdb:5984/
      - DOCS_PATH=/data/
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_DBS=${COUCHDB_DBS}
    volumes:
      - ./data-generator.py:/code/data-generator.py:z
      - ./data/json_docs/:/data/:z
    restart: always
