version: '3.7'

services:
  dbt:
    image: medicmobile/dataemon:latest
    restart: always
    environment:
      - POSTGRES_USER=${DBT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DBT_POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TABLE=${POSTGRES_TABLE}
      - POSTGRES_SCHEMA=${DBT_POSTGRES_SCHEMA}
      - POSTGRES_HOST=postgres
      - ROOT_POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - DATAEMON_INITAL_PACKAGE=https://github.com/medic/cht-pipeline.git#function-material

  postgres:
    image: postgres:12
    restart: always
    volumes:
      - ./init-dbt-resources.sh:/docker-entrypoint-initdb.d/init-dbt-resources.sh:z
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DBT_POSTGRES_USER=${DBT_POSTGRES_USER}
      - DBT_POSTGRES_PASSWORD=${DBT_POSTGRES_PASSWORD}
      - DBT_POSTGRES_SCHEMA=${DBT_POSTGRES_SCHEMA}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TABLES=${POSTGRES_TABLE} ${POSTGRES_TABLE}_sentinel
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}