version: '3.7'

services:
  logstash:
    depends_on:
      - couchdb

  couchdb:
    image: couchdb
    restart: always
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}

  bootstrap:
    build: ./data/
    depends_on:
      - couchdb
    restart: on-failure:5
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_DBS=${COUCHDB_DBS}

  generator:
    image: python:3
    depends_on:
      - couchdb
    command: >
      bash -c "mkdir /data/ && tar -xzf /json_docs.tar.gz -C /data/ --strip-components=1 && python3 /code/data-generator.py"
    environment:
      - COUCHDB_URL=http://couchdb:5984/
      - DOCS_PATH=/data/
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_DBS=${COUCHDB_DBS}
    volumes:
      - ./data/data-generator.py:/code/data-generator.py:z
      - ./data/json_docs.tar.gz/:/json_docs.tar.gz:z
    restart: always
