services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init-dbt-resources.sh:/docker-entrypoint-initdb.d/init-dbt-resources.sh:z
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DBT_POSTGRES_USER=${DBT_POSTGRES_USER}
      - DBT_POSTGRES_PASSWORD=${DBT_POSTGRES_PASSWORD}
      - DBT_POSTGRES_SCHEMA=${DBT_POSTGRES_SCHEMA}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TABLES=${COUCHDB_DBS}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}

  postgrest:
    image: postgrest/postgrest
    depends_on:
      - postgres
    restart: always
    ports:
      - 3000:3000
    environment:
      - PGRST_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-postgres}:5432/${POSTGRES_DB}
      - PGRST_DB_SCHEMA=${POSTGRES_SCHEMA}
      # CHANGE FOR PROD!!!!
      - PGRST_DB_ANON_ROLE=${POSTGRES_USER}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
