version: '3.7'

services:
  logstash:
    image: medicmobile/cht-logstash-couchdb:latest
    build: ./logstash/
    restart: always
    volumes:
      - type: bind
        source: ./logstash/couch-seq
        target: /tmp/couchdb
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_HOST=${COUCHDB_HOST}
      - COUCHDB_DBS=${COUCHDB_DBS}
      - COUCHDB_PORT=${COUCHDB_PORT}
      - COUCHDB_SEQ=/tmp/couchdb/sequence_path.txt
      - COUCHDB_SECURE=${COUCHDB_SECURE:-true}
      - HTTP_ENDPOINT=postgrest:3000

  dbt:
    platform: linux/amd64
    image: medicmobile/dataemon:latest
    build: ./dbt/
    working_dir: /dbt/
    environment:
      - POSTGRES_HOST=${DBT_POSTGRES_HOST}
      - POSTGRES_USER=${DBT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DBT_POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TABLE=${POSTGRES_TABLE}
      - POSTGRES_SCHEMA=${DBT_POSTGRES_SCHEMA}
      - ROOT_POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - CHT_PIPELINE_BRANCH_URL=${CHT_PIPELINE_BRANCH_URL}
      - DATAEMON_INTERVAL=${DATAEMON_INTERVAL}

