version: '3.7'

services:
  logstash:
    image: medicmobile/cht-logstash-couchdb:latest
    build: ./logstash/
    restart: always
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_HOST=${COUCHDB_HOST}
      - COUCHDB_PORT=${COUCHDB_PORT}
      - COUCHDB_SEQ=/tmp/couchdb/sequence_path.txt
      - COUCHDB_SECURE=${COUCHDB_SECURE:-true}
      - HTTP_ENDPOINT=postgrest:3000

  superset:
    build: 
      context: ./superset/
    environment:
      - SUPERSET_PASSWORD=${SUPERSET_PASSWORD:-password}
      - SUPERSET_ADMIN_EMAIL=${SUPERSET_ADMIN_EMAIL:-user@superset.com}
      - SUPERSET_SSH_TUNNELING=${SUPERSET_SSH_TUNNELING}
    ports:
      - 8080:8088

  dbt:
    platform: linux/amd64
    image: medicmobile/dataemon:latest
    environment:
      - POSTGRES_HOST=${DBT_POSTGRES_HOST}
      - POSTGRES_USER=${DBT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DBT_POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TABLE=${POSTGRES_TABLE}
      - POSTGRES_SCHEMA=${DBT_POSTGRES_SCHEMA}
      - ROOT_POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - DATAEMON_INITAL_PACKAGE=${CHT_PIPELINE_BRANCH_URL}

