version: '3.7'

services:
  logstash:
    image: medicmobile/cht-logstash-couchdb:latest
    build: ./logstash/
    restart: always
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_DB=${COUCHDB_DB}
      - COUCHDB_HOST=${COUCHDB_HOST}
      - POSTGRES_TABLE=${POSTGRES_TABLE}
      - HTTP_ENDPOINT=postgrest:3000

  postgrest:
    image: postgrest/postgrest
    restart: always
    environment:
      - PGRST_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-postgres}:5432/${POSTGRES_DB}
      - PGRST_DB_SCHEMA=${POSTGRES_SCHEMA}
      # CHANGE FOR PROD!!!!
      - PGRST_DB_ANON_ROLE=${POSTGRES_USER}
