version: '3.7'

services:
  logstash:
    image: medicmobile/cht-logstash-couchdb:latest
    build: ./logstash/
    restart: always
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_HOST=${COUCHDB_HOST}
      - COUCHDB_DBS=${COUCHDB_DBS}
      - COUCHDB_PORT=${COUCHDB_PORT}
      - COUCHDB_SEQ=/tmp/couchdb/sequence_path.txt
      - COUCHDB_SECURE=${COUCHDB_SECURE:-true}
      - HTTP_ENDPOINT=postgrest:3000

  dbt:
    platform: linux/amd64
    image: medicmobile/dataemon:latest
    build: ./dbt/
    working_dir: /dbt/
    environment:
      - POSTGRES_HOST=${DBT_POSTGRES_HOST}
      - POSTGRES_USER=${DBT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DBT_POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TABLE=${POSTGRES_TABLE}
      - POSTGRES_SCHEMA=${DBT_POSTGRES_SCHEMA}
      - ROOT_POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - CHT_PIPELINE_BRANCH_URL=${CHT_PIPELINE_BRANCH_URL}
      - DATAEMON_INTERVAL=${DATAEMON_INTERVAL}

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  redis-worker:
    build: ./redis-worker/
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_KEY=${REDIS_KEY}
      - POSTGREST_ENDPOINT=postgrest:3000
    depends_on:
      - redis
    restart: unless-stopped
volumes:
  redis-data:
