version: '3.7'

services:
  couchdb:
    image: public.ecr.aws/medic/cht-couchdb:4.8.0
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
  initialize_couchdb:
    image: curlimages/curl
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - couchdb
    command: ["sh","-c","sleep 15 && curl -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} -X PUT couchdb:5984/_users &&  curl -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} -X PUT couchdb:5984/medic"]
