services:
  postgres:
    image: postgres:16
    restart: always
    volumes:
      - ./postgres/init-dbt-resources.sh:/docker-entrypoint-initdb.d/init-dbt-resources.sh:z
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TABLES=${COUCHDB_DBS}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}