version: '3.7'

services:
  dbt:
    image: medicmobile/dataemon:latest
    environment:
      - POSTGRES_USER=${DBT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DBT_POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TABLE=${POSTGRES_TABLE}
      - POSTGRES_SCHEMA=${DBT_POSTGRES_SCHEMA}
      - ROOT_POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - DATAEMON_INITAL_PACKAGE=https://github.com/medic/cht-pipeline.git#first_release

  postgres:
    image: postgres:12
    restart: always
    volumes:
      - ./init-dbt-resources.sh:/docker-entrypoint-initdb.d/init-dbt-resources.sh:z
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DBT_POSTGRES_USER=${DBT_POSTGRES_USER}
      - DBT_POSTGRES_PASSWORD=${DBT_POSTGRES_PASSWORD}
      - DBT_POSTGRES_SCHEMA=${DBT_POSTGRES_SCHEMA}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TABLES=${POSTGRES_TABLE} ${POSTGRES_TABLE}_sentinel
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}


  redis:
    image: redis:latest
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data

  superset:
    env_file: superset/.env
    image: apache/superset
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: unless-stopped
    ports:
      - 8088:8088
    depends_on:
      - redis
    volumes:
      - ./superset/:/app/docker/

  superset-init:
    image: apache/superset
    container_name: superset_init
    command: ["/app/docker/docker-init.sh"]
    env_file: docker/.env
    depends_on:
      - redis
      - postgres
    user: "root"
    volumes:
      - ./superset/:/app/docker/

