services:
  couch2pg:
    build: ./couch2pg/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_HOST=${COUCHDB_HOST}
      - COUCHDB_DBS=${COUCHDB_DBS}
      - COUCHDB_PORT=${COUCHDB_PORT}
      - COUCHDB_SECURE=${COUCHDB_SECURE:-true}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=5432
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - POSTGRES_TABLE=${POSTGRES_TABLE}
    restart: always

  dbt:
    build: ./dbt/
    working_dir: /dbt/
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TABLE=${POSTGRES_TABLE}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - ROOT_POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - CHT_PIPELINE_BRANCH_URL=${CHT_PIPELINE_BRANCH_URL}
      - DATAEMON_INTERVAL=${DATAEMON_INTERVAL}
      - DBT_PACKAGE_TARBALL_URL=${DBT_PACKAGE_TARBALL_URL}
      - DBT_BATCH_SIZE=${DBT_BATCH_SIZE}
      - PYTHONUNBUFFERED=1
