version: '3.7'

services:
  couchdb:
    image: public.ecr.aws/medic/cht-couchdb:4.8.0
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
