version: '3.7'

services:
  logstash:
    image: medicmobile/cht-logstash-couchdb:latest
    build: ./logstash/
    restart: always
    volumes:
      - type: bind
        source: ./logstash
        target: /tmp/couchdb
