apiVersion: apps/v1
kind: Deployment
metadata:
  name: cht-sync-couch2pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cht-sync
  template:
    metadata:
      labels:
        app: cht-sync
    spec:
      automountServiceAccountToken: false
      containers:
        - name: couch2pg
          image: medicmobile/cht-sync-couch2pg:{{ .Values.image_tag | default "latest" }}
          resources:
            limits:
              cpu: {{ (.Values.couch2pg).cpu_limit | default "500m" }}
              memory: {{ (.Values.couch2pg).memory_limit | default "1Gi" }}
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.postgres.host | default "postgres" }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgres.port | default "5432" | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
            - name: POSTGRES_TABLE
              value: {{ .Values.postgres.table }}
            - name: POSTGRES_SCHEMA
              value: {{ .Values.postgres.schema }}
            - name: COUCHDB_USER
              value: {{ .Values.couchdb.user }}
            - name: COUCHDB_PASSWORD
              value: {{ .Values.couchdb.password }}
            - name: COUCHDB_HOST
              value: {{ .Values.couchdb.host }}
            - name: COUCHDB_DBS
              value: {{ .Values.couchdb.dbs }}
            - name: COUCHDB_PORT
              value: {{ .Values.couchdb.port | quote }}
            - name: COUCHDB_SECURE
              value: {{ .Values.couchdb.secure | quote }}
