# templates/logstash.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cht-sync-logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cht-sync
  template:
    metadata:
      labels:
        app: cht-sync
    spec:
      automountServiceAccountToken: false
      containers:
        - name: logstash
          image: medicmobile/cht-logstash-couchdb:{{ .Values.image_tag | default "latest" }}
          resources:
            limits:
              cpu: {{ (.Values.logstash).cpu_limit | default "2" }}
              memory: {{ (.Values.logstash).memory_limit | default "2Gi" }}
          env:
            - name: COUCHDB_USER
              value: {{ .Values.couchdb.user }}
            - name: COUCHDB_PASSWORD
              value: {{ .Values.couchdb.password }}
            - name: COUCHDB_HOST
              value: {{ .Values.couchdb.host }}
            - name: COUCHDB_DBS
              value: {{ .Values.couchdb.dbs }}
            - name: COUCHDB_PORT
              value: {{ .Values.couchdb.port | quote }}
            - name: COUCHDB_SECURE
              value: {{ .Values.couchdb.secure | default "false" | quote }}
            - name: COUCHDB_SEQ # don't allow this to be changed
              value: "/tmp/couchdb/sequence_path.txt"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_KEY
              value: {{ (.Values.redis).key | default "couchdb" }}
