# templates/postgres.yaml

{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cht-sync-postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: cht-sync-postgres
  template:
    metadata:
      labels:
        app: cht-sync-postgres
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgres-c
          image: postgres:16
          resources:
            limits:
              cpu: {{ (.Values.postgres).cpu_limit | default "1000m" }}
              memory: {{ (.Values.postgres).memory_limit | default "2Gi" }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: {{ .Values.postgres.port | default "5432" }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-shm
              mountPath: /dev/shm
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-shm
          emptyDir:
            medium: Memory
            sizeLimit: {{ (.Values.postgres).memory_limit | default "2Gi" }}
{{- end }}
