# templates/postgrest.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cht-sync-postgrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cht-sync
      inner.service: postgrest
  template:
    metadata:
      labels:
        app: cht-sync
        inner.service: postgrest
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgrest
          image: postgrest/postgrest
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
          env:
            - name: PGRST_DB_URI
              value: {{ printf "postgres://%s:%s@%s:5432/%s" .Values.postgres.user .Values.postgres.password .Values.postgres.host .Values.postgres.db }}
            - name: PGRST_DB_SCHEMA
              value: "{{ .Values.postgres.schema }}"
            - name: PGRST_DB_ANON_ROLE
              value: "{{ .Values.postgres.user }}"
