# templates/postgrest.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cht-sync-postgrest
spec:
  serviceName: postgrest
  replicas: 1
  selector:
    matchLabels:
      app: cht-sync
      inner.service: postgrest
  template:
    metadata:
      labels:
        app: cht-sync
        inner.service: postgrest
    spec:
      containers:
        - name: postgrest
          image: postgrest/postgrest
          # Add environment variables and volume mounts as needed
          env:
            - name: PGRST_DB_URI
              value: "postgres://postgres:postgres@postgres:5432/data"
            - name: PGRST_DB_SCHEMA
              value: "{{ .Values.postgres.schema }}"
            - name: PGRST_DB_ANON_ROLE
              value: "{{ .Values.postgres.user }}"
