# templates/postgres.yaml

{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cht-sync-postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: cht-sync
      inner.service: postgres
  template:
    metadata:
      labels:
        app: cht-sync
        inner.service: postgres
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgres-c
          image: postgres:13
          resources:
            limits:
              cpu: {{ (.Values.postgres).cpu_limit | default "1000m" }}
              memory: {{ (.Values.postgres).memory_limit | default "2Gi" }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
          ports:
            - containerPort: {{ .Values.postgres.port | default "5432" }}

  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.postgres.storageSize | default "1Gi" }}
{{- end }}
