#!/bin/sh
set -e

export PGPASSWORD=$POSTGRES_PASSWORD

echo Setting up defaults

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';
    CREATE SCHEMA IF NOT EXISTS $POSTGRES_SCHEMA AUTHORIZATION $POSTGRES_USER;

    GRANT USAGE ON SCHEMA $POSTGRES_SCHEMA TO $POSTGRES_USER;
    GRANT SELECT ON ALL TABLES IN SCHEMA $POSTGRES_SCHEMA TO $POSTGRES_USER;
    GRANT SELECT ON ALL SEQUENCES IN SCHEMA $POSTGRES_SCHEMA TO $POSTGRES_USER;
    GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA $POSTGRES_SCHEMA TO $POSTGRES_USER;

    CREATE SCHEMA IF NOT EXISTS $POSTGRES_SCHEMA AUTHORIZATION $POSTGRES_USER;
EOSQL
