name: Build cht-sync containers

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push logstash
        uses: docker/build-push-action@v4
        with:
          context: ./logstash
          file: ./logstash/Dockerfile
          push: true
          tags: medicmobile/cht-logstash-couchdb:${{ env.BRANCH }}

      - name: Build and push dataemon
        uses: docker/build-push-action@v4
        with:
          context: ./dbt
          file: ./dbt/Dockerfile
          push: true
          tags: medicmobile/dataemon:${{ env.BRANCH }}

      - name: Build and push redis-worker
        uses: docker/build-push-action@v4
        with:
          context: ./redis-worker
          file: ./redis-worker/Dockerfile
          push: true
          tags: dockermedic/cht-sync-redis-worker:${{ env.BRANCH }}
