name: Build cht-sync containers

on: [push, pull_request]

jobs:

  build:
    name: Compile the app
    runs-on: ubuntu-18.04

    steps:
    - name: Get Docker Hub username
      id: get-docker-hub-username
      run: echo '::set-output name=dockerhub_username::${{ secrets.DOCKERHUB_USERNAME }}'
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: steps.get-docker-hub-username.outputs.dockerhub_username
    - uses: actions/checkout@v2
    - name: Docker Build
      run: docker-compose build
