name: Conventional commits
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  lint_pr_title:
    name: Lint PR title
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install commitlint
        run: |
          npm install @commitlint/config-conventional
          npm install commitlint@latest
      - name: Lint title
        run: npx --no -- commitlint <<< "${{ github.event.pull_request.title }}"
