name: Test

on: [push, pull_request]

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - run: npm ci
      - run: npm ci
        working-directory: ./couch2pg
      - run: npm run lint
      - run: npm run test

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Get Docker Hub username
        id: get-docker-hub-username
        run: echo '::set-output name=dockerhub_username::${{ secrets.DOCKERHUB_USERNAME }}'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.get-docker-hub-username.outputs.dockerhub_username
      - run: npm ci
      - name: Start containers
        run: docker compose --env-file ./tests/.e2e-env up -d
      - name: Sleep for 60 seconds
        run: sleep 60s
      - name: Run e2e tests
        run: npm run test:e2e

